package app.revolt.exception

enum class RevoltPermissionApiType(val type: String) {
    ManageChannel("ManageChannel"),
    ManageServer("ManageServer"),
    ManagePermissions("ManagePermissions"),
    ManageRole("ManageRole"),
    ManageCustomisation("ManageCustomisation"),
    KickMembers("KickMembers"),
    BanMembers("BanMembers"),
    TimeoutMembers("TimeoutMembers"),
    AssignRoles("AssignRoles"),
    ChangeNickname("ChangeNickname"),
    ManageNicknames("ManageNicknames"),
    ChangeAvatar("ChangeAvatar"),
    RemoveAvatars("RemoveAvatars"),
    ViewChannel("ViewChannel"),
    ReadMessageHistory("ReadMessageHistory"),
    SendMessage("SendMessage"),
    ManageMessages("ManageMessages"),
    ManageWebhooks("ManageWebhooks"),
    InviteOthers("InviteOthers"),
    SendEmbeds("SendEmbeds"),
    UploadFiles("UploadFiles"),
    Masquerade("Masquerade"),
    React("React"),
    Connect("Connect"),
    Speak("Speak"),
    Video("Video"),
    MuteMembers("MuteMembers"),
    DeafenMembers("DeafenMembers"),
    MoveMembers("MoveMembers"),
    GrantAllSafe("GrantAllSafe"),
    GrantAll("GrantAll");
}